name: some_calendar
description: Custom calendar (multi select, single select, date range) for Flutter
version: 1.3.0
homepage: https://github.com/agryva/Some-Calendar.git
license: MIT

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  jiffy: ^5.0.0
  intl: ^0.17.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: roboto-regular
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
    - family: playfair-regular
      fonts:
        - asset: fonts/playfair.ttf
